version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data

  myapp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: my-go-app

    depends_on:
      - db
      - redis

    environment:
      - DB=host=db user=posgres password=postgres dbname=postgres port=5432 sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    ports:
      - 8080:8080

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  db_data:
  redis_data: