version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my-postgres

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

  myapp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: my-go-app

    depends_on:
      - db

    environment:
      - DB=host=db user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} port=${DB_PORT} sslmode=disable

    ports:
      - "${APP_PORT}:8080"

volumes:
  db_data